tasks:
  - name: terraform
    before: |
      source ./scripts/install-terraform-cli.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./scripts/install-aws-cli.sh
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
